name: Integracao Continua de Codigo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Valida Codigo
        run: mvn -B validate --file pom.xml
      - name: Compila Codigo
        run: mvn -B clean compile --file pom.xml
      - name: Checkstyle
        run: mvn -B checkstyle:checkstyle -Dcheckstyle.skip=false --file pom.xml
      - name: Testes Unitarios
        run: mvn -B test --file pom.xml
      - name: Testes Unitarios
        run: mvn -B verify -P integration-test --file pom.xml
      - name: Cobertura de Codigo
        run: mvn -B clean verify -P all-tests --file pom.xml